### PR TITLE
fix: name activation price label in dashboard

### LINKED ISSUE #328: Dashboard: wrong label in activated AENS names
### Context information

application version: latest dev deployment
device: 
browser: 
operating system: 

### What is expected?
For AENS names claimed via auction, it should not display "Fixed price" but "Auction" or sth. else instead. When I remember correctly we had it defined back then. Not sure if it was ever correctly implemented though.

### What is actually happening?
image

### PR DESCRIPTION
**Pull request by lukeromanowicz**
## Description
Resolves #328

## Demo
image

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] My change does not require a change to the documentation.

### CODE REVIEW

File: src/utils/adapters.js [hunk 1]
```diff
@@ -80,10 +80,8 @@ export function adaptChainNames(chainNames, blockHeight) {
         chainName.info.active_from,
         blockHeight,
       ),
-      isAuction: isAuction(chainName),
-      price: isAuction(chainName)
-        ? formatAettosToAe(chainName.last_bid.tx.name_fee)
-        : formatAettosToAe(chainName.info.claims[chainName.info.claims.length - 1].tx.name_fee),
+      isAuction: isAuction(chainName.name),
+      price: formatAettosToAe(chainName.info.claims[chainName.info.claims.length - 1].tx.name_fee),
```
Comment (lukeromanowicz) [inline src/utils/adapters.js:84]: Apparently there was some change in the mdw since we implemented this code and this code can be used to get the price for both auctioned name and a direct buy

**Comment by marc0olo** [comment]
@lukeromanowicz I think "Auction" is sufficient as label

**Comment by lukeromanowicz** [comment]
@marc0olo roger that, adjusted :+1:

File: src/utils/adapters.js (hunk 1 above)
Comment (janmichek) [reply src/utils/adapters.js:84]: Have you tried this? Its a new addition to JS https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

**Review by janmichek — APPROVED** [review]
Nice change, I like 👍 
Please check my suggestion

**Comment by lukeromanowicz** [comment]
@janmichek love it, thank you! I haven't seen that before

**Comment by janmichek** [comment]
> @janmichek love it, thank you! I haven't seen that before

Cool, yea its a new thing

**Comment by michele-franchi** [comment]
Are PR preview links broken?

**Review by michele-franchi — APPROVED** [review]
Good job 🚀
