### PR TITLE
fix: Account transactions counter bug

### LINKED ISSUE #41: Account transactions counter bug
Account details display uncorrect amount of total transactions when filtered in the table.

Tracking https://github.com/aeternity/ae_mdw/issues/1236

### PR DESCRIPTION
**Pull request by janmichek**
## Description
resolves #41 

## Demo
https://github.com/aeternity/aescan/assets/15363559/195cc37a-2d92-403d-bdfd-aa9de07cc223

## Checklist:
- [x] fix account transaction counter
- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)

### CODE REVIEW

**Review by lukeromanowicz — CHANGES_REQUESTED** [review]
Amazing! One of the most annoying bugs is fixed! I requested one small improvement but overall looks great. Thank you for fixing it!

File: src/components/AccountTransactionsPanel.vue [hunk 1]
```diff
@@ -43,6 +43,10 @@ const pageIndex = ref(1)
 
 const limit = computed(() => isDesktop() ? 10 : 3)
 
+if (process.client) {
+  fetchAccountTransactionsCount(route.params.id, selectedTxType.value.typeQuery)
```
[the remark this answers is not in the document]
Comment (janmichek) [reply src/components/AccountTransactionsPanel.vue]: True, wasn't sure about that. Fixed

**Review by michele-franchi — APPROVED** [review]
It works well, good job!

File: src/components/AccountTransactionsPanel.vue [hunk 2]
```diff
@@ -43,6 +43,8 @@ const pageIndex = ref(1)
 
 const limit = computed(() => isDesktop() ? 10 : 3)
 
+fetchAccountTransactionsCount(route.params.id, selectedTxType.value.typeQuery)
```
Comment (lukeromanowicz) [inline src/components/AccountTransactionsPanel.vue:46]: please use await useAsyncData similarly to https://github.com/aeternity/aescan/pull/273/files. Otherwise, the backend will not wait until this request is finished and return the response prematurely.

**Review by lukeromanowicz — CHANGES_REQUESTED** [review]

**Review by CharisSiarampalis — APPROVED** [review]

File: src/components/AccountTransactionsPanel.vue (hunk 2 above)
Comment (janmichek) [reply src/components/AccountTransactionsPanel.vue]: fixed

**Review by lukeromanowicz — APPROVED** [review]
Looks nice, thank you!
