### PR TITLE
fix: display correct token holder values

### LINKED ISSUE #461: floating point error in aeScan token balances
### Steps to reproduce
Visit https://aescan.io/tokens/ct_xtk8rSz9suPb6D6VLquyfVji25FcnFRDjn3dnn5mmvHsPiESt

### What is expected?
Correct values should be displayed, see
image

### What is actually happening?
Wrong values are displayed
image

### PR DESCRIPTION
**Pull request by lukeromanowicz**
## Description
Resolves #461

Issue was caused by imprecise number division

## Demo
image

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] My change does not require a change to the documentation.

### CODE REVIEW

File: src/utils/adapters.js [hunk 1]
```diff
@@ -400,8 +401,10 @@ export function adaptTokenEvents(events, blockHeight) {
 export function adaptTokenHolders(tokenHolders, tokenDetails) {
   const formattedData = tokenHolders.data.map(holder => ({
     address: holder.accountId,
-    amount: holder.amount / (10 ** tokenDetails.decimals),
-    percentage: (holder.amount / (10 ** (tokenDetails.decimals - 2))) / tokenDetails.totalSupply,
+    amount: (new BigNumber(holder.amount)).dividedBy(10 ** tokenDetails.decimals).toNumber(),
+    percentage: ((new BigNumber(holder.amount))
```
Comment (janmichek) [inline src/utils/adapters.js:405]: Is there a need for so many brackets?

Comment (lukeromanowicz) [reply src/utils/adapters.js:405]: 1 set too much. I wonder why the linter didn't catch that. Thanks

**Review by CharisSiarampalis — APPROVED** [review]

**Comment by lukeromanowicz** [comment]
Merging without Michele's approval as agreed during the daily
