### PR TITLE
fix: displaying auctions

### LINKED ISSUE #1087: Can't see a list of name auction bids
### Steps to reproduce
- open https://testnet.aescan.io/names?type=in-auction
- click on a link to https://testnet.aescan.io/names/auctiob.chain
- see Name Not Found page

### What is expected?
To see the list of bids.

### What is actually happening?
I'm getting the Name Not Found page.

### PR DESCRIPTION
**Pull request by janmichek**
## Description
fixes #1087
partly resolve https://github.com/aeternity/aescan/issues/909

## Demo
image

## Checklist:

- [ ] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by janmichek** [comment]
@mmpetarpeshev There is some problem with infrasturcture. It says it needs some update

**Comment by mmpetarpeshev** [comment]
> @mmpetarpeshev There is some problem with infrasturcture. It says it needs some update

PLEASE USE SLACK ,IF YOU WANT THAT TO BE SEEN QUICKLY!!!

File: src/composables/search.js [hunk 1]
```diff
@@ -28,6 +33,18 @@ export const useSearchStore = defineStore('search', () => {
     return await $fetch(`/api/search/${id}`)
   }
 
+  async function isNameAvailable(name) {
```
Comment (davidyuk) [inline src/composables/search.js:36]: Confusing naming, I understand "available" as can be claimed, but this name is already claimed. I would name it `isNameClaimed`, `isNameExist` or `isNameRegistered`

File: src/composables/search.js [hunk 2]
```diff
@@ -28,6 +33,18 @@ export const useSearchStore = defineStore('search', () => {
...
+    try {
+      await axios.get(`${MIDDLEWARE_URL}/names/${name}`)
+      return true
+    } catch (error) {
+      if (error.response.status === 404) {
+        return false
+      }
+      return null
```
Comment (davidyuk) [inline src/composables/search.js:44]: Do some logging so as not to swallow the error. I don't think `null` is useful, propose to return `false` instead

File: src/server/api/names/history.js [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+  const { data } = await axios.get(url)
+
+  return adaptNameHistory(data)
+})
+
+export function adaptNameHistory(actions) {
+  const formattedData = actions.data.map(action => {
+    return {
+      type: action.type,
+      hash: action.payload.sourceTxHash || action.payload.callTxHash || action.payload.hash,
```
Comment (davidyuk) [inline src/server/api/names/history.js:23]: more strict version:
```
      hash: action.payload.sourceTxHash ?? action.payload.callTxHash ?? action.payload.hash,
```

File: src/server/api/names/[id].js [hunk 4]
```diff
@@ -0,0 +1,136 @@
...
+    entity: 'key-blocks',
+    limit: 1,
+  })
+  const { data } = await axios.get(url)
+  return data.data[0]
+}
+
+function adaptName(name, blockHeight, blockTime) {
+  const lastBid = name?.lastBid
+  const hash = name.hash || name.lastBid.tx.nameId
```
Comment (davidyuk) [inline src/server/api/names/[id].js:66]:
```
  const hash = name.hash ?? name.lastBid.tx.nameId
```

File: src/server/api/names/[id].js [hunk 5]
```diff
@@ -0,0 +1,136 @@
...
+
+  const hasRawPointers = allPointers
+    ? allPointers.some(pointer => isAddressValid(pointer.id, Encoding.Bytearray))
+    : null
+
+  return customPointers.map(pointer => {
+    return {
+      key: pointer.key,
+      pointer: hasRawPointers ? decode(pointer.id).toString() : pointer.id,
+      isRawPointer: hasRawPointers,
```
Comment (davidyuk) [inline src/server/api/names/[id].js:133]: Why are all pointers marked as raw if only one is raw?

**Comment by janmichek** [comment]
@davidyuk Thanks for suggestions! Will go through them.

File: src/server/api/names/[id].js (hunk 5 above)
Comment (janmichek) [reply src/server/api/names/[id].js:133]: its because its either all pointers are raw or none. So the condition to check only one is raw should suffice

File: src/composables/search.js (hunk 2 above)
Comment (janmichek) [reply src/composables/search.js:44]: The error is signalized to user thru UI. But you are right, changed to false.

File: src/server/api/names/[id].js (hunk 5 above)
Comment (davidyuk) [reply src/server/api/names/[id].js:133]: Technically, a raw pointer doesn't interfere with any other pointers, or is this a UI restriction?

Comment (janmichek) [reply src/server/api/names/[id].js:133]: No its not UI restriction. I don't remember precisely, but it was hard to make it work, some investigation was done. I prefer to leave it like this unless proven the approach is wrong. There was no complaint so far

File: src/composables/search.js (hunk 2 above)
Comment (janmichek) [reply src/composables/search.js:44]: Make sense
