### PR TITLE
fix: display account details if accounts owns tokens and has never been seen on the network 

### LINKED ISSUE #460: display account details if accounts owns tokens and has never been seen on the network
### Context information
account details are currently not displayed although the account owns AEX-9 tokens

### Steps to reproduce
visit https://aescan.io/accounts/ak_PXVUiBzByjNX4VSTmay18fjDwrkUnwFbyNTy3NBG55GLF6M3r

the account got AEX-9 tokens with this tx:
- https://aescan.io/transactions/th_hiZV7wpVAwxrpHMJ3E5VCwKJDRBb1pU73cLbZE1jBvUqQCume

the account owns AEX-9 tokens, see:
- https://aescan.io/tokens/ct_xtk8rSz9suPb6D6VLquyfVji25FcnFRDjn3dnn5mmvHsPiESt

image

### What is expected?
the account details as well as owned tokens should be displayed

### PR DESCRIPTION
**Pull request by janmichek**
## Description
fixes #460

## Demo

https://github.com/aeternity/aescan/assets/15363559/a3f2ede2-0257-4ede-91d3-d00fd3c6c857

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] change not existent account with tokens UX

### CODE REVIEW

File: src/components/AppTab.vue [hunk 1]
```diff
@@ -12,13 +12,18 @@ const props = defineProps({
...
+    default: false,
+  },
 })
 
 const isActive = ref(false)
 const registerTab = inject('registerTab')
 
 registerTab({
   title: props.title,
+  isPreselected: props.isPreselected,
```
Comment (janmichek) [inline src/components/AppTab.vue:26]: I found this `preselected` feature as easiest to implement

**Review by lukeromanowicz — APPROVED** [review]
It's working pretty well. Nicely done

File: src/components/AccountDetailsPanel.vue [hunk 2]
```diff
@@ -21,7 +21,7 @@
       class="account-details-panel__not-existent">
       The account has never been seen in the network.
       <br>
-      Details will be displayed after the first interaction with this account.
+      Details will be displayed once the first transaction from the account is sent.
```
Comment (michele-franchi) [inline src/components/AccountDetailsPanel.vue:24]:
```suggestion
      Details will be displayed once the account is involved in a transaction.
```

I think it's better because the account could also be the recipient and not the sender.

**Review by michele-franchi — CHANGES_REQUESTED** [review]
I suggested a change and could you also have a look at the following flashing issue?
Thanks

https://github.com/aeternity/aescan/assets/11598532/ca4ec946-2403-467d-9a39-004d262e66a0

File: src/components/AccountDetailsPanel.vue (hunk 2 above)
Comment (janmichek) [reply src/components/AccountDetailsPanel.vue]: ok, accepted

**Review by CharisSiarampalis — APPROVED** [review]

**Comment by michele-franchi** [comment]
@janmichek I still see the issue about flashing tabs I reported with the video

**Comment by janmichek** [comment]
> @janmichek I still see the issue about flashing tabs I reported with the video

The issue was already present in production. Fixed

**Review by michele-franchi — APPROVED** [review]
It looks good but I found out if you reload the page sometimes the transactions tab is selected and sometimes the tokens tab is selected, demo:

https://github.com/aeternity/aescan/assets/11598532/82115782-ac9e-4aa4-9d22-78dbbeb05ac0

I approve in advance but could you check the issue?

**Comment by marc0olo** [comment]
@michele-franchi do we have a plan to also adjust the message? might be a bit misleading right now if the account has received tokens 🤔

**Comment by michele-franchi** [comment]
@marc0olo do you think it's still misleading? 
Previously it was: 
`Details will be displayed after the first interaction with this account.`

**Comment by marc0olo** [comment]
I would say sth. like "the direct involvement in a native transaction" and add a note like "the account can already receive custom tokens"

**Comment by michele-franchi** [comment]
Ok then we can adjust it to:
```
The account has never been seen in the network.
Details will be displayed once the account is directly involved in a native transaction, but the account can already receive custom tokens.
```

@janmichek @marc0olo

**Comment by janmichek** [comment]
@lukeromanowicz Could you help me to validate the solution I made in last commit?
https://github.com/aeternity/aescan/pull/488/commits/51416afe14086fc59198cb9b221855ed23af5f45

The problem was that after reloading, we got random results. Sometimes was selected Transaction tab, sometimes the Tokens tab. The symptom seems to me like data fetching was not waiting for themselves somehow. As shown here https://github.com/aeternity/aescan/pull/488#pullrequestreview-1610277064

My solution fixed that, but I would like you to help me identify if there will not be any side effects or if the solution isn't overkill. Many thanks

**Comment by lukeromanowicz** [comment]
@janmichek your solution is 100% correct. I would implement it the same way :+1:

**Comment by janmichek** [comment]
> @janmichek your solution is 100% correct. I would implement it the same way 👍

Nice, Thanks for collaboration
